###
GET http://localhost:3000/api/alumnos HTTP/1.1
Content-Type: application/json

###
GET http://localhost:3000/api/alumnos/2 HTTP/1.1

###
DELETE http://localhost:3000/api/alumnos/2 HTTP/1.1

###
PUT http://localhost:3000/api/alumnos/1 HTTP/1.1
Content-Type: application/json

{
    "nombre": "Borja",
    "edad": 22,
    "domicilio": { "calle": "San Francisco Solano", "num": 36, "localidad": "Montilla" }
}

###
POST http://localhost:3000/api/alumnos/agregar HTTP/1.1
Content-Type: application/json

{
    "nombre": "Gerardo",
    "edad": 23,
    "domicilio": { "calle": "Medico cabello", "num": 17, "localidad": "Montilla"
    }
} 